# Scenarios de test realistes - TIM Consulting
# QALITAS WEB + GMAO PRO
# Generes a partir du contexte reel des produits

SCENARIOS = [

    # ============================================================
    # SCENARIO 1 - GMAO PRO : Gestion des techniciens
    # Traitement a risque eleve : donnees RH + geolocalisation
    # ============================================================
    {
        "id_traitement": "TRT-GMAO-001",
        "nom_traitement": "Gestion des techniciens de maintenance",
        "systeme": "GMAO PRO",
        "responsable": "Responsable RH - TIM Consulting",
        "donnees_collectees": ["nom", "prenom", "email", "telephone", "adresse", "localisation_GPS", "matricule", "photo"],
        "categories_donnees": ["identite", "contact", "localisation", "professionnel"],
        "donnees_sensibles": False,
        "donnees_penales": False,
        "finalite": "Gestion des ressources humaines et suivi des interventions de maintenance",
        "finalite_definie": True,
        "base_legale": "contrat",
        "consentement_valide": False,
        "consentement_retire": False,
        "consentement_conditionne_service": False,
        "service_conditionne_consentement": False,
        "autorisation_donnees_penales": False,
        "personnes_concernees": ["employes", "techniciens"],
        "destinataires": ["responsable_maintenance", "direction"],
        "transfert_etranger": False,
        "adequation_ou_garanties_documentees": False,
        "autorisation_inpdp_transfert": False,
        "niveau_protection_adequat": False,
        "risque_securite_nationale": False,
        "duree_conservation": "5 ans apres fin de contrat",
        "duree_conservation_definie": True,
        "duree_depassee": False,
        "donnees_minimisees": True,
        "donnees_exactes": True,
        "respect_vie_privee": True,
        "declaration_inpdp": True,
        "garanties_specifiques": False,
        "mesures_securite": ["authentification", "chiffrement_transit", "controle_acces"],
        "chiffrement_actif": False,
        "tests_securite_reguliers": False,
        "controle_acces_physique": True,
        "confidentialite_post_traitement": True,
        "privacy_by_design": False,
        "privacy_by_default": False,
        "consultation_autorite_si_risque_residuel": False,
        "processus_droits_personnes": True,
        "information_personnes_concernees": True,
        "modalites_droits_accessibles": True,
        "collecte_indirecte": False,
        "information_collecte_indirecte": False,
        "consentement_collecte_indirecte": False,
        "information_transfert_fournie": False,
        "opposition_ignoree": False,
        "decision_automatisee": False,
        "garanties_decision_auto": False,
        "dsar_hors_delai": False,
        "violation_donnees": False,
        "notification_72h": False,
        "notification_personnes": False,
        "violation_documentee": False,
        "risque_eleve": True,
        "aipd_realisee": False,
        "mise_en_production": True,
        "analyse_risque_avant_production": False,
        "contrat_sous_traitance": False,
        "garanties_sous_traitant": False,
        "registre_traitement": False,
        "traitement_grande_echelle": False,
        "dpo_designe": False,
        "missions_dpo_garanties": False,
        "politique_protection_donnees": False,
        "revue_periodique_mesures": False,
    },

    # ============================================================
    # SCENARIO 2 - GMAO PRO : Geolocalisation techniciens (mobile)
    # Traitement critique : donnees de localisation en temps reel
    # ============================================================
    {
        "id_traitement": "TRT-GMAO-002",
        "nom_traitement": "Geolocalisation des techniciens en intervention",
        "systeme": "GMAO PRO Mobile",
        "responsable": "Responsable Maintenance - TIM Consulting",
        "donnees_collectees": ["nom", "prenom", "localisation_GPS", "matricule"],
        "categories_donnees": ["identite", "localisation"],
        "donnees_sensibles": False,
        "donnees_penales": False,
        "finalite": "Suivi en temps reel des interventions et optimisation des tournees",
        "finalite_definie": True,
        "base_legale": "contrat",
        "consentement_valide": False,
        "consentement_retire": False,
        "consentement_conditionne_service": False,
        "service_conditionne_consentement": False,
        "autorisation_donnees_penales": False,
        "personnes_concernees": ["employes", "techniciens"],
        "destinataires": ["responsable_maintenance"],
        "transfert_etranger": False,
        "adequation_ou_garanties_documentees": False,
        "autorisation_inpdp_transfert": False,
        "niveau_protection_adequat": False,
        "risque_securite_nationale": False,
        "duree_conservation": "30 jours",
        "duree_conservation_definie": True,
        "duree_depassee": False,
        "donnees_minimisees": True,
        "donnees_exactes": True,
        "respect_vie_privee": False,
        "declaration_inpdp": False,
        "garanties_specifiques": False,
        "mesures_securite": ["chiffrement_transit"],
        "chiffrement_actif": False,
        "tests_securite_reguliers": False,
        "controle_acces_physique": False,
        "confidentialite_post_traitement": True,
        "privacy_by_design": False,
        "privacy_by_default": False,
        "consultation_autorite_si_risque_residuel": False,
        "processus_droits_personnes": False,
        "information_personnes_concernees": False,
        "modalites_droits_accessibles": False,
        "collecte_indirecte": False,
        "information_collecte_indirecte": False,
        "consentement_collecte_indirecte": False,
        "information_transfert_fournie": False,
        "opposition_ignoree": False,
        "decision_automatisee": False,
        "garanties_decision_auto": False,
        "dsar_hors_delai": False,
        "violation_donnees": False,
        "notification_72h": False,
        "notification_personnes": False,
        "violation_documentee": False,
        "risque_eleve": True,
        "aipd_realisee": False,
        "mise_en_production": True,
        "analyse_risque_avant_production": False,
        "contrat_sous_traitance": False,
        "garanties_sous_traitant": False,
        "registre_traitement": False,
        "traitement_grande_echelle": False,
        "dpo_designe": False,
        "missions_dpo_garanties": False,
        "politique_protection_donnees": False,
        "revue_periodique_mesures": False,
    },

    # ============================================================
    # SCENARIO 3 - QALITAS : Gestion des audits QHSE
    # Traitement moyen : donnees auditeurs et audites
    # ============================================================
    {
        "id_traitement": "TRT-QALITAS-001",
        "nom_traitement": "Gestion des audits QHSE",
        "systeme": "QALITAS WEB",
        "responsable": "Responsable QHSE - TIM Consulting",
        "donnees_collectees": ["nom", "prenom", "email", "matricule", "photo"],
        "categories_donnees": ["identite", "contact", "professionnel"],
        "donnees_sensibles": False,
        "donnees_penales": False,
        "finalite": "Planification et suivi des audits qualite, securite et environnement",
        "finalite_definie": True,
        "base_legale": "obligation_legale",
        "consentement_valide": False,
        "consentement_retire": False,
        "consentement_conditionne_service": False,
        "service_conditionne_consentement": False,
        "autorisation_donnees_penales": False,
        "personnes_concernees": ["employes", "auditeurs", "audites"],
        "destinataires": ["direction_qualite", "auditeurs_externes"],
        "transfert_etranger": True,
        "adequation_ou_garanties_documentees": False,
        "autorisation_inpdp_transfert": False,
        "niveau_protection_adequat": False,
        "risque_securite_nationale": False,
        "duree_conservation": "10 ans",
        "duree_conservation_definie": True,
        "duree_depassee": False,
        "donnees_minimisees": True,
        "donnees_exactes": True,
        "respect_vie_privee": True,
        "declaration_inpdp": True,
        "garanties_specifiques": False,
        "mesures_securite": ["authentification", "controle_acces"],
        "chiffrement_actif": False,
        "tests_securite_reguliers": False,
        "controle_acces_physique": True,
        "confidentialite_post_traitement": True,
        "privacy_by_design": False,
        "privacy_by_default": False,
        "consultation_autorite_si_risque_residuel": False,
        "processus_droits_personnes": True,
        "information_personnes_concernees": True,
        "modalites_droits_accessibles": True,
        "collecte_indirecte": False,
        "information_collecte_indirecte": False,
        "consentement_collecte_indirecte": False,
        "information_transfert_fournie": False,
        "opposition_ignoree": False,
        "decision_automatisee": False,
        "garanties_decision_auto": False,
        "dsar_hors_delai": False,
        "violation_donnees": False,
        "notification_72h": False,
        "notification_personnes": False,
        "violation_documentee": False,
        "risque_eleve": False,
        "aipd_realisee": False,
        "mise_en_production": True,
        "analyse_risque_avant_production": False,
        "contrat_sous_traitance": False,
        "garanties_sous_traitant": False,
        "registre_traitement": True,
        "traitement_grande_echelle": False,
        "dpo_designe": False,
        "missions_dpo_garanties": False,
        "politique_protection_donnees": True,
        "revue_periodique_mesures": False,
    },

    # ============================================================
    # SCENARIO 4 - QALITAS : Gestion des non-conformites
    # Traitement faible : donnees responsables
    # ============================================================
    {
        "id_traitement": "TRT-QALITAS-002",
        "nom_traitement": "Gestion des non-conformites et actions correctives",
        "systeme": "QALITAS WEB",
        "responsable": "Responsable Qualite - TIM Consulting",
        "donnees_collectees": ["nom", "prenom", "email", "matricule"],
        "categories_donnees": ["identite", "contact", "professionnel"],
        "donnees_sensibles": False,
        "donnees_penales": False,
        "finalite": "Suivi et traitement des non-conformites et actions correctives ISO 9001",
        "finalite_definie": True,
        "base_legale": "obligation_legale",
        "consentement_valide": False,
        "consentement_retire": False,
        "consentement_conditionne_service": False,
        "service_conditionne_consentement": False,
        "autorisation_donnees_penales": False,
        "personnes_concernees": ["employes"],
        "destinataires": ["responsable_qualite", "direction"],
        "transfert_etranger": False,
        "adequation_ou_garanties_documentees": False,
        "autorisation_inpdp_transfert": False,
        "niveau_protection_adequat": False,
        "risque_securite_nationale": False,
        "duree_conservation": "5 ans",
        "duree_conservation_definie": True,
        "duree_depassee": False,
        "donnees_minimisees": True,
        "donnees_exactes": True,
        "respect_vie_privee": True,
        "declaration_inpdp": True,
        "garanties_specifiques": False,
        "mesures_securite": ["authentification", "controle_acces", "chiffrement_transit"],
        "chiffrement_actif": True,
        "tests_securite_reguliers": True,
        "controle_acces_physique": True,
        "confidentialite_post_traitement": True,
        "privacy_by_design": True,
        "privacy_by_default": True,
        "consultation_autorite_si_risque_residuel": False,
        "processus_droits_personnes": True,
        "information_personnes_concernees": True,
        "modalites_droits_accessibles": True,
        "collecte_indirecte": False,
        "information_collecte_indirecte": False,
        "consentement_collecte_indirecte": False,
        "information_transfert_fournie": False,
        "opposition_ignoree": False,
        "decision_automatisee": False,
        "garanties_decision_auto": False,
        "dsar_hors_delai": False,
        "violation_donnees": False,
        "notification_72h": False,
        "notification_personnes": False,
        "violation_documentee": False,
        "risque_eleve": False,
        "aipd_realisee": False,
        "mise_en_production": True,
        "analyse_risque_avant_production": True,
        "contrat_sous_traitance": False,
        "garanties_sous_traitant": False,
        "registre_traitement": True,
        "traitement_grande_echelle": False,
        "dpo_designe": False,
        "missions_dpo_garanties": False,
        "politique_protection_donnees": True,
        "revue_periodique_mesures": True,
    },

    # ============================================================
    # SCENARIO 5 - GMAO PRO : Sous-traitance maintenance
    # Traitement a risque : donnees fournisseurs + sous-traitants
    # ============================================================
    {
        "id_traitement": "TRT-GMAO-003",
        "nom_traitement": "Gestion des sous-traitants et fournisseurs maintenance",
        "systeme": "GMAO PRO",
        "responsable": "Responsable Achats - TIM Consulting",
        "donnees_collectees": ["nom", "prenom", "email", "telephone", "adresse"],
        "categories_donnees": ["identite", "contact", "professionnel"],
        "donnees_sensibles": False,
        "donnees_penales": False,
        "finalite": "Gestion des achats et sous-traitance pour les activites de maintenance",
        "finalite_definie": True,
        "base_legale": "contrat",
        "consentement_valide": False,
        "consentement_retire": False,
        "consentement_conditionne_service": False,
        "service_conditionne_consentement": False,
        "autorisation_donnees_penales": False,
        "personnes_concernees": ["sous_traitants", "fournisseurs"],
        "destinataires": ["responsable_maintenance", "direction_financiere"],
        "transfert_etranger": True,
        "adequation_ou_garanties_documentees": False,
        "autorisation_inpdp_transfert": False,
        "niveau_protection_adequat": False,
        "risque_securite_nationale": False,
        "duree_conservation": "10 ans",
        "duree_conservation_definie": True,
        "duree_depassee": False,
        "donnees_minimisees": True,
        "donnees_exactes": True,
        "respect_vie_privee": True,
        "declaration_inpdp": False,
        "garanties_specifiques": False,
        "mesures_securite": ["authentification"],
        "chiffrement_actif": False,
        "tests_securite_reguliers": False,
        "controle_acces_physique": False,
        "confidentialite_post_traitement": False,
        "privacy_by_design": False,
        "privacy_by_default": False,
        "consultation_autorite_si_risque_residuel": False,
        "processus_droits_personnes": False,
        "information_personnes_concernees": False,
        "modalites_droits_accessibles": False,
        "collecte_indirecte": True,
        "information_collecte_indirecte": False,
        "consentement_collecte_indirecte": False,
        "information_transfert_fournie": False,
        "opposition_ignoree": False,
        "decision_automatisee": False,
        "garanties_decision_auto": False,
        "dsar_hors_delai": False,
        "violation_donnees": False,
        "notification_72h": False,
        "notification_personnes": False,
        "violation_documentee": False,
        "risque_eleve": False,
        "aipd_realisee": False,
        "mise_en_production": True,
        "analyse_risque_avant_production": False,
        "contrat_sous_traitance": False,
        "garanties_sous_traitant": False,
        "registre_traitement": False,
        "traitement_grande_echelle": False,
        "dpo_designe": False,
        "missions_dpo_garanties": False,
        "politique_protection_donnees": False,
        "revue_periodique_mesures": False,
    },

    # ============================================================
    # SCENARIO 6 - QALITAS : Clients TIM (multisite)
    # Traitement grande echelle : clients dans plusieurs pays
    # ============================================================
    {
        "id_traitement": "TRT-QALITAS-003",
        "nom_traitement": "Gestion des comptes clients QALITAS WEB",
        "systeme": "QALITAS WEB",
        "responsable": "Direction Commerciale - TIM Consulting",
        "donnees_collectees": ["nom", "prenom", "email", "telephone", "adresse", "matricule"],
        "categories_donnees": ["identite", "contact", "professionnel"],
        "donnees_sensibles": False,
        "donnees_penales": False,
        "finalite": "Gestion des acces et comptes utilisateurs clients QALITAS dans plusieurs pays",
        "finalite_definie": True,
        "base_legale": "contrat",
        "consentement_valide": False,
        "consentement_retire": False,
        "consentement_conditionne_service": False,
        "service_conditionne_consentement": False,
        "autorisation_donnees_penales": False,
        "personnes_concernees": ["clients", "utilisateurs_externes"],
        "destinataires": ["support_technique", "direction_commerciale"],
        "transfert_etranger": True,
        "adequation_ou_garanties_documentees": False,
        "autorisation_inpdp_transfert": False,
        "niveau_protection_adequat": False,
        "risque_securite_nationale": False,
        "duree_conservation": "Duree du contrat + 3 ans",
        "duree_conservation_definie": True,
        "duree_depassee": False,
        "donnees_minimisees": True,
        "donnees_exactes": True,
        "respect_vie_privee": True,
        "declaration_inpdp": False,
        "garanties_specifiques": False,
        "mesures_securite": ["authentification", "chiffrement_transit", "controle_acces"],
        "chiffrement_actif": False,
        "tests_securite_reguliers": False,
        "controle_acces_physique": False,
        "confidentialite_post_traitement": True,
        "privacy_by_design": False,
        "privacy_by_default": False,
        "consultation_autorite_si_risque_residuel": False,
        "processus_droits_personnes": False,
        "information_personnes_concernees": False,
        "modalites_droits_accessibles": False,
        "collecte_indirecte": False,
        "information_collecte_indirecte": False,
        "consentement_collecte_indirecte": False,
        "information_transfert_fournie": False,
        "opposition_ignoree": False,
        "decision_automatisee": False,
        "garanties_decision_auto": False,
        "dsar_hors_delai": False,
        "violation_donnees": False,
        "notification_72h": False,
        "notification_personnes": False,
        "violation_documentee": False,
        "risque_eleve": True,
        "aipd_realisee": False,
        "mise_en_production": True,
        "analyse_risque_avant_production": False,
        "contrat_sous_traitance": False,
        "garanties_sous_traitant": False,
        "registre_traitement": False,
        "traitement_grande_echelle": True,
        "dpo_designe": False,
        "missions_dpo_garanties": False,
        "politique_protection_donnees": False,
        "revue_periodique_mesures": False,
    },
]
